<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Company>Gibbed</Company>
    <Authors>Gibbed</Authors>
    <Description>http://gib.me/</Description>
    <Copyright>Copyright © Gibbed 2020</Copyright>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>..\..\bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gibbed.Disrupt.Packing\Gibbed.Disrupt.Packing.csproj" />
  </ItemGroup>
</Project>
