name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - .github/**
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md
      - .github/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug]
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

      - name: Create artifacts
        shell: pwsh
        run: |
          $version = "$env:GITHUB_RUN_ID"
          git log . > git-log.txt
          7z a -r -tzip -mx=9 "-x!*/LICENSE.txt" "-x!*/.git*" disrupt_$version.zip ./LICENSE.txt ./README.txt git-log.txt bin/*.exe bin/*.dll bin/projects
          7z a -r -tzip -mx=9 "-x!*/LICENSE.txt" "-x!*/.git*" disrupt_${version}_with-debug-symbols.zip ./LICENSE.txt ./README.txt git-log.txt bin/*.exe bin/*.dll bin/*.pdb bin/projects

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: disrupt-${{ matrix.configuration }}
          path: '*.zip'